"""Writes a Visio VBA module (.bas) that draws the same map natively.

The .vsdx is the primary deliverable; this module is the escape hatch. It draws
real Visio shapes through the object model, so the result is guaranteed to be
whatever the installed Visio thinks a shape is — useful if a locked-down build
refuses a hand-authored package, and useful as a starting point for anyone who
wants to keep editing the map in code.

The emitted file is pure ASCII: every character outside ASCII is written as a
ChrW() call, because .bas import reads the file in the system code page and
arrows (U+2192) do not survive that round trip.
"""

import layout as L

CHUNK = 22          # shapes per generated Sub, to stay clear of VBA's 64KB
                    # per-procedure limit
LITERAL = 120       # max characters per emitted string literal


def _rgb(hex_color: str) -> str:
    h = hex_color.lstrip("#")
    return f"RGB({int(h[0:2], 16)},{int(h[2:4], 16)},{int(h[4:6], 16)})"


def _literal_chunks(text: str):
    """Split into runs of ASCII text and single non-ASCII characters."""
    buf = ""
    for ch in text:
        if 32 <= ord(ch) < 127 and ch != '"':
            buf += ch
            if len(buf) >= LITERAL:
                yield ("s", buf)
                buf = ""
        else:
            if buf:
                yield ("s", buf)
                buf = ""
            if ch == '"':
                yield ("s", '""')
            else:
                yield ("c", ord(ch))
    if buf:
        yield ("s", buf)


def _assign_text(var: str, text: str, indent: str = "    "):
    """Emit `t = ...` / `t = t & ...` lines that build up a string safely."""
    lines = [f'{indent}{var} = ""']
    for kind, value in _literal_chunks(text):
        piece = f'"{value}"' if kind == "s" else f"ChrW({value})"
        lines.append(f"{indent}{var} = {var} & {piece}")
    return lines


PRELUDE = '''Attribute VB_Name = "MaintenanceProcessMap"
' ---------------------------------------------------------------------------
' Maintenance, end to end - process map
'
' Generated by visio/build.py. Do not hand-edit; edit visio/content.py and
' regenerate so the .vsdx and this macro stay in step.
'
' To run: open Visio, press Alt+F11, File > Import File... and pick this .bas,
' then press F5 on BuildMaintenanceProcessMap.
' ---------------------------------------------------------------------------
Option Explicit

Private Const PAGE_W As Double = {page_w}
Private Const PAGE_H As Double = {page_h}

Private pg As Visio.Page
Private t As String

Public Sub BuildMaintenanceProcessMap()
    Dim doc As Visio.Document

    Set doc = Visio.Application.Documents.Add("")
    Set pg = doc.Pages(1)
    pg.Name = "Process Map"

    With pg.PageSheet
        .CellsU("PageWidth").FormulaU = PAGE_W & " in"
        .CellsU("PageHeight").FormulaU = PAGE_H & " in"
        .CellsU("PrintPageOrientation").FormulaU = "2"
        .CellsU("DrawingSizeType").FormulaU = "3"
    End With

    Application.ScreenUpdating = False
{calls}
    Application.ScreenUpdating = True

    If Not Visio.Application.ActiveWindow Is Nothing Then
        Visio.Application.ActiveWindow.ViewFit = visFitPage
    End If
End Sub

' --- helpers ---------------------------------------------------------------

' Draws a rectangle. x/y are top-left in the layout's top-down space; this is
' the one place the y axis is flipped for Visio's bottom-left origin.
Private Function B(x As Double, y As Double, w As Double, h As Double, _
                   nm As String, fill As String, ln As String, _
                   wt As Double, rnd As Double, ha As Integer, _
                   va As Integer, mg As Double) As Visio.Shape
    Dim s As Visio.Shape
    Set s = pg.DrawRectangle(x, PAGE_H - y - h, x + w, PAGE_H - y)
    s.Name = nm

    If fill = "" Then
        s.CellsU("FillPattern").FormulaU = "0"
    Else
        s.CellsU("FillPattern").FormulaU = "1"
        s.CellsU("FillForegnd").FormulaU = fill
    End If

    If ln = "" Then
        s.CellsU("LinePattern").FormulaU = "0"
    Else
        s.CellsU("LinePattern").FormulaU = "1"
        s.CellsU("LineColor").FormulaU = ln
        s.CellsU("LineWeight").FormulaU = wt & " in"
        s.CellsU("Rounding").FormulaU = rnd & " in"
    End If

    s.CellsU("Para.HorzAlign").FormulaU = ha
    s.CellsU("VerticalAlign").FormulaU = va
    s.CellsU("LeftMargin").FormulaU = mg & " in"
    s.CellsU("RightMargin").FormulaU = mg & " in"
    s.CellsU("TopMargin").FormulaU = mg & " in"
    s.CellsU("BottomMargin").FormulaU = mg & " in"
    s.CellsU("Para.SpLine").FormulaU = "-1.15"

    Set B = s
End Function

' Applies character formatting to the [b, e) character range of a shape.
Private Sub F(s As Visio.Shape, b As Long, e As Long, fnt As String, _
              sz As Double, col As String, bold As Integer, trk As Double)
    Dim r As Integer
    With s.Characters
        .Begin = b
        If e < 0 Then e = .CharCount
        .End = e
        r = .CharPropsRow(0) + 1
    End With
    s.CellsU("Char.Font[" & r & "]").FormulaU = """" & fnt & """"
    s.CellsU("Char.Size[" & r & "]").FormulaU = sz & " pt"
    s.CellsU("Char.Color[" & r & "]").FormulaU = col
    s.CellsU("Char.Style[" & r & "]").FormulaU = bold
    s.CellsU("Char.Letterspace[" & r & "]").FormulaU = trk & " in"
End Sub

' Draws a polyline through a flat x1,y1,x2,y2,... array, flipping y as it goes.
Private Function P(pts() As Double, col As String, wt As Double, _
                   dash As Integer, arrow As Integer, nm As String) As Visio.Shape
    Dim i As Long
    Dim xy() As Double
    ReDim xy(LBound(pts) To UBound(pts))

    For i = LBound(pts) To UBound(pts) Step 2
        xy(i) = pts(i)
        xy(i + 1) = PAGE_H - pts(i + 1)
    Next i

    Dim s As Visio.Shape
    Set s = pg.DrawPolyline(xy, 0)
    s.Name = nm
    s.CellsU("LineColor").FormulaU = col
    s.CellsU("LineWeight").FormulaU = wt & " in"
    s.CellsU("LinePattern").FormulaU = dash
    s.CellsU("LineCap").FormulaU = "1"
    s.CellsU("EndArrow").FormulaU = arrow
    s.CellsU("EndArrowSize").FormulaU = "2"
    s.CellsU("FillPattern").FormulaU = "0"
    If (UBound(pts) - LBound(pts) + 1) > 4 Then
        s.CellsU("Rounding").FormulaU = "0.06 in"
    End If
    Set P = s
End Function

'''


def _emit_box(box: L.Box, lines):
    fill = _rgb(box.fill) if box.fill else ""
    line = _rgb(box.line) if box.line else ""
    lines.append(
        f'    Set s = B({box.x:.4f}, {box.y:.4f}, {box.w:.4f}, {box.h:.4f}, '
        f'"{box.name}", "{fill}", "{line}", {box.weight:.4f}, '
        f'{box.rounding:.4f}, {box.halign}, {box.valign}, {box.margin:.4f})'
    )

    if not box.runs:
        return

    full = "".join(chunk for chunk, _ in box.runs)
    lines.extend(_assign_text("t", full))
    lines.append("    s.Text = t")

    offset = 0
    for chunk, style_key in box.runs:
        font, size_pt, color, bold = L.STYLES[style_key]
        tracking = L.TRACKING.get(style_key, 0.0)
        end = offset + len(chunk)
        lines.append(
            f'    F s, {offset}, {end}, "{font}", {size_pt}, '
            f'"{_rgb(color)}", {1 if bold else 0}, {tracking:.4f}'
        )
        offset = end


def _emit_poly(poly: L.Poly, lines):
    flat = []
    for x, y in poly.pts:
        flat.extend([x, y])
    lines.append(f"    ReDim p({len(flat) - 1})")
    for i, value in enumerate(flat):
        lines.append(f"    p({i}) = {value:.4f}")
    lines.append(
        f'    P p, "{_rgb(poly.color)}", {poly.weight:.4f}, '
        f'{2 if poly.dashed else 1}, {4 if poly.end_arrow else 0}, "{poly.name}"'
    )


def write(path: str, boxes, polys, page_h: float, page_w: float = L.PAGE_W):
    # One flat list so the chunking is uniform across both shape kinds.
    items = [("box", b) for b in boxes] + [("poly", p) for p in polys]
    groups = [items[i:i + CHUNK] for i in range(0, len(items), CHUNK)]

    body = []
    for gi, group in enumerate(groups, start=1):
        body.append(f"Private Sub Draw{gi:03d}()")
        body.append("    Dim s As Visio.Shape")
        body.append("    Dim p() As Double")
        for kind, item in group:
            if kind == "box":
                _emit_box(item, body)
            else:
                _emit_poly(item, body)
        body.append("End Sub")
        body.append("")

    calls = "\n".join(f"    Draw{i:03d}" for i in range(1, len(groups) + 1))
    header = PRELUDE.format(page_w=f"{page_w:.4f}", page_h=f"{page_h:.4f}",
                            calls=calls)

    with open(path, "w", encoding="ascii", newline="\r\n") as fh:
        fh.write(header)
        fh.write("\n".join(body))

    return len(groups)
