/**
 * Demo content: personas, community finds, transfer bonuses, balances and alerts.
 * Pure data — no imports from server modules so scripts can reuse it.
 */

export interface SeedPersona {
  email: string;
  name: string;
  handle: string;
  bio: string;
  homeAirport: string;
  plan: "free" | "pro";
}

export const SEED_PERSONAS: SeedPersona[] = [
  { email: "explorer@demo.kestrel.travel", name: "Demo Explorer", handle: "explorer", bio: "Trying Kestrel. Home base NYC. Chasing lie-flat seats to Japan.", homeAirport: "JFK", plan: "pro" },
  { email: "maven@demo.kestrel.travel", name: "Priya N.", handle: "mileage_maven", bio: "Aeroplan + Avios tactician. 1.2M points redeemed and counting.", homeAirport: "YYZ", plan: "pro" },
  { email: "jules@demo.kestrel.travel", name: "Jules A.", handle: "jetsetjules", bio: "Hotels first, flights second. Hyatt Globalist, Maldives regular.", homeAirport: "SFO", plan: "pro" },
  { email: "pointsdad@demo.kestrel.travel", name: "Marcus T.", handle: "pointsdad", bio: "Family of four on points. Economy pro, business dreamer.", homeAirport: "ORD", plan: "free" },
  { email: "suite@demo.kestrel.travel", name: "Lena K.", handle: "suitelife", bio: "First class or bust. Qsuites, ANA F, Lufthansa F enjoyer.", homeAirport: "LAX", plan: "pro" },
  { email: "anna@demo.kestrel.travel", name: "Anna R.", handle: "avgeek_anna", bio: "Aviation nerd. I book awards for the aircraft, not the destination.", homeAirport: "SEA", plan: "free" },
  { email: "redeye@demo.kestrel.travel", name: "Dev P.", handle: "theredeye", bio: "Last-minute award hunter. Alerts are my love language.", homeAirport: "BOS", plan: "free" },
];

export interface SeedFind {
  handle: string;
  title: string;
  body: string;
  origin?: string;
  destination?: string;
  carrier?: string;
  cabin?: "economy" | "premium" | "business" | "first";
  programId?: string;
  miles?: number;
  taxesUsd?: number;
  travelDate?: string;
  tags: string[];
  likes: number;
  daysAgo: number;
}

export const SEED_FINDS: SeedFind[] = [
  {
    handle: "suitelife",
    title: "ANA First JFK→HND for 72.5k Virgin points — the unicorn landed",
    body: "Set an alert for Nov and it fired at 2:14am. Transferred Amex → Virgin instantly (30% bonus running!), booked by 2:30. Taxes $168. The Suite is absurd: 43\" screen, sliding door, and the Hibiki pour is generous. Tip: ANA opens F space in waves ~14 days out, so set the window tight.",
    origin: "JFK",
    destination: "HND",
    carrier: "NH",
    cabin: "first",
    programId: "virgin-atlantic-flying-club",
    miles: 72500,
    taxesUsd: 168,
    travelDate: "2026-11-18",
    tags: ["ana-first", "virgin-atlantic", "sweet-spot", "japan"],
    likes: 418,
    daysAgo: 1,
  },
  {
    handle: "mileage_maven",
    title: "Lufthansa Allegris J YYZ→MUC on Aeroplan, 70k + $92",
    body: "Aeroplan priced it as Atlantic zone 4,001–6,000 miles. No surcharges on LH via Aeroplan which is the whole trick. Allegris Classic seat with the big screen; wifi worked over Greenland. Chase → Aeroplan 25% bonus made it ~56k UR.",
    origin: "YYZ",
    destination: "MUC",
    carrier: "LH",
    cabin: "business",
    programId: "aeroplan",
    miles: 70000,
    taxesUsd: 92,
    travelDate: "2026-10-02",
    tags: ["aeroplan", "lufthansa", "allegris", "europe"],
    likes: 262,
    daysAgo: 2,
  },
  {
    handle: "jetsetjules",
    title: "Park Hyatt Maldives 5 nights, 35k/night off-peak",
    body: "Booked for late May (off-peak), cat 8 at 35k. Seaplane transfer is $700pp which stings, but the overwater villa is $2,400/night cash so we're at 6.8¢/point. Globalist breakfast + 4pm checkout. Kestrel's hotel search flagged the off-peak dates — would have missed it.",
    destination: "MLE",
    cabin: "first",
    programId: "world-of-hyatt",
    miles: 175000,
    taxesUsd: 0,
    travelDate: "2027-05-22",
    tags: ["hyatt", "maldives", "hotels", "off-peak"],
    likes: 311,
    daysAgo: 3,
  },
  {
    handle: "pointsdad",
    title: "4× economy ORD→LIS on TAP for 22k Flying Blue each (promo rewards)",
    body: "Flying Blue promo rewards for Portugal, −25%. $110 taxes each. Capital One → Flying Blue 1:1, instant. Family summer trip for under 90k total. Economy on the A330neo is fine for 7 hours, kids slept.",
    origin: "ORD",
    destination: "LIS",
    carrier: "TP",
    cabin: "economy",
    programId: "flying-blue",
    miles: 22000,
    taxesUsd: 110,
    travelDate: "2027-07-08",
    tags: ["flying-blue", "promo", "family", "europe"],
    likes: 144,
    daysAgo: 4,
  },
  {
    handle: "avgeek_anna",
    title: "Qsuites SEA→DOH→MLE with Avios: 70k + $63 — Q-suite A350-1000 both legs",
    body: "Booked via Qatar Privilege Club Avios (moved from BA Club 1:1). SEA–DOH priced at 70k in J. Second leg DOH–MLE added 28k, so ~98k total. Suite 7K on the 1000 has extra legroom for the window-facing seat.",
    origin: "SEA",
    destination: "MLE",
    carrier: "QR",
    cabin: "business",
    programId: "qatar-privilege-club",
    miles: 98000,
    taxesUsd: 63,
    travelDate: "2027-02-12",
    tags: ["qsuites", "avios", "qatar", "maldives"],
    likes: 198,
    daysAgo: 5,
  },
  {
    handle: "theredeye",
    title: "Last-minute: BOS→LHR in BA Club Suite, 50k Avios + $380 (ouch) 48h out",
    body: "Needed to be in London for a funeral. BA releases 2+ J seats close-in on most LHR flights. Taxes hurt from BOS but the alternative was $4,100 cash. Club Suite door closes, decent sleep. Used Chase UR → BA.",
    origin: "BOS",
    destination: "LHR",
    carrier: "BA",
    cabin: "business",
    programId: "british-airways-club",
    miles: 50000,
    taxesUsd: 380,
    travelDate: "2026-09-29",
    tags: ["british-airways", "last-minute", "club-suite"],
    likes: 87,
    daysAgo: 6,
  },
  {
    handle: "mileage_maven",
    title: "Turkish 7.5k: ORD→DEN on United for 7,500 miles — still works in 2026",
    body: "Domestic United economy via Miles&Smiles: 7.5k + $5.60. Have to book on the TK site now, no more email. Capital One / Citi → Turkish 1:1. Best short-haul value in North America, full stop.",
    origin: "ORD",
    destination: "DEN",
    carrier: "UA",
    cabin: "economy",
    programId: "turkish-miles-smiles",
    miles: 7500,
    taxesUsd: 6,
    travelDate: "2026-10-24",
    tags: ["turkish", "domestic", "sweet-spot", "united"],
    likes: 233,
    daysAgo: 7,
  },
  {
    handle: "suitelife",
    title: "Cathay First HKG→LAX on Alaska: 70k — found 2 seats 11 months out",
    body: "Alaska's 2024 chart put CX F Asia→NA at 70k one-way. Taxes $140. Caviar and the Krug are back. Pro tip: Alaska search only shows CX if you search the exact nonstop.",
    origin: "HKG",
    destination: "LAX",
    carrier: "CX",
    cabin: "first",
    programId: "alaska-mileage-plan",
    miles: 70000,
    taxesUsd: 140,
    travelDate: "2027-08-15",
    tags: ["cathay", "alaska", "first-class"],
    likes: 301,
    daysAgo: 8,
  },
  {
    handle: "avgeek_anna",
    title: "SQ A350-900ULR SFO→SIN in J for 107k KrisFlyer — booked the 18-hour sleep",
    body: "Saver space in J on the ULR shows up ~3-4 weeks out more than people think. Amex → KrisFlyer took 18 hours. Book the Book the Cook lobster thermidor. Taxes $62.",
    origin: "SFO",
    destination: "SIN",
    carrier: "SQ",
    cabin: "business",
    programId: "singapore-krisflyer",
    miles: 107000,
    taxesUsd: 62,
    travelDate: "2027-03-03",
    tags: ["singapore", "krisflyer", "ultra-long-haul"],
    likes: 176,
    daysAgo: 9,
  },
  {
    handle: "jetsetjules",
    title: "Conrad Bora Bora Nui 5 nights for 380k Hilton — 5th night free + Aspire",
    body: "Standard rate 95k/night, 5th free = 380k. $1,800/night cash in July. Overwater villas aren't guaranteed on points but Diamond got us upgraded day 2. Amex → Hilton 1:2 so this was 190k MR.",
    destination: "BOB",
    cabin: "first",
    programId: "hilton-honors",
    miles: 380000,
    taxesUsd: 0,
    travelDate: "2027-07-20",
    tags: ["hilton", "bora-bora", "5th-night-free"],
    likes: 209,
    daysAgo: 10,
  },
  {
    handle: "pointsdad",
    title: "Hyatt Regency Maui 4 nights at 25k — breakfast for 4 included (Globalist friend booked)",
    body: "Cat 6 standard. Cash was $780/night + resort fee (waived on points!). Chase UR → Hyatt 1:1. The lazy river is the whole vacation for the kids.",
    destination: "OGG",
    programId: "world-of-hyatt",
    miles: 100000,
    taxesUsd: 0,
    travelDate: "2027-04-05",
    tags: ["hyatt", "hawaii", "family", "resort-fee"],
    likes: 121,
    daysAgo: 11,
  },
  {
    handle: "theredeye",
    title: "Avianca LifeMiles: EWR→FRA Lufthansa J 63k + $48, booked 6 days out",
    body: "LifeMiles site was flaky but the award posted. No YQ. Not the Allegris plane (747-8 upper deck, which is honestly better for a night flight).",
    origin: "EWR",
    destination: "FRA",
    carrier: "LH",
    cabin: "business",
    programId: "avianca-lifemiles",
    miles: 63000,
    taxesUsd: 48,
    travelDate: "2026-10-01",
    tags: ["lifemiles", "lufthansa", "747"],
    likes: 98,
    daysAgo: 12,
  },
  {
    handle: "mileage_maven",
    title: "Emirates A380 F JFK→MXP for 136k Skywards — the fifth freedom shower flight",
    body: "Emirates' own program is the only sane way for F now. Taxes $110. Milan→NYC return on Aeroplan EK J for 95k. Shower spa at 40,000 ft remains undefeated.",
    origin: "JFK",
    destination: "MXP",
    carrier: "EK",
    cabin: "first",
    programId: "emirates-skywards",
    miles: 136000,
    taxesUsd: 110,
    travelDate: "2027-01-14",
    tags: ["emirates", "a380", "first-class", "fifth-freedom"],
    likes: 254,
    daysAgo: 13,
  },
  {
    handle: "avgeek_anna",
    title: "JAL F HND→SFO booked via Alaska for 80k (old chart honored!)",
    body: "Alaska honoured the pre-devaluation price on a date I had on hold. JAL F is quieter than ANA F — fewer suites, better sleep. Salon Coffee + Hibiki 21 on this flight.",
    origin: "HND",
    destination: "SFO",
    carrier: "JL",
    cabin: "first",
    programId: "alaska-mileage-plan",
    miles: 80000,
    taxesUsd: 55,
    travelDate: "2026-12-02",
    tags: ["jal", "alaska", "first-class", "japan"],
    likes: 167,
    daysAgo: 14,
  },
  {
    handle: "pointsdad",
    title: "Southwest companion pass + 2 kids: MDW→CUN RT for 24k each way",
    body: "Not glamorous, but 4 people to Cancún for 96k Rapid Rewards + $150 taxes total. Chase → Southwest 1:1. Hyatt Ziva Cancun on 25k/night with the Hyatt card free night.",
    origin: "MDW",
    destination: "CUN",
    carrier: "WN",
    cabin: "economy",
    programId: "southwest-rapid-rewards",
    miles: 24000,
    taxesUsd: 38,
    travelDate: "2027-03-27",
    tags: ["southwest", "family", "mexico", "companion-pass"],
    likes: 73,
    daysAgo: 15,
  },
  {
    handle: "suitelife",
    title: "Lufthansa First FRA→IAD, 110k Aeroplan + $160, First Class Terminal included",
    body: "Opened 13 days out as always. Aeroplan prices LH F at 110k for 4,001–6,000 mile Atlantic. The FCT in Frankfurt with the Porsche ride to the plane is half the fun. Caviar service still excellent.",
    origin: "FRA",
    destination: "IAD",
    carrier: "LH",
    cabin: "first",
    programId: "aeroplan",
    miles: 110000,
    taxesUsd: 160,
    travelDate: "2026-10-18",
    tags: ["lufthansa", "first-class", "aeroplan", "fct"],
    likes: 287,
    daysAgo: 16,
  },
  {
    handle: "jetsetjules",
    title: "Andaz Tokyo 3 nights at 30k (cat 7) during cherry blossom — booked 11 months out",
    body: "Peak dates would be 35k; grabbed the last standard nights for late March. Cash was $900/night. Chase → Hyatt. Rooftop bar view of Tokyo Tower, and the Toranomon Hills location is underrated for Ginza access.",
    destination: "HND",
    programId: "world-of-hyatt",
    miles: 90000,
    taxesUsd: 0,
    travelDate: "2027-03-28",
    tags: ["hyatt", "tokyo", "sakura", "hotels"],
    likes: 142,
    daysAgo: 17,
  },
  {
    handle: "theredeye",
    title: "Air France La Première is bookable with points now? Sort of — Flying Blue Platinum/Ultimate only",
    body: "PSA: if you see 'La Première' on Flying Blue it's only for Ultimate/Platinum members and prices at 220k+. Business CDG→JFK was 55k + $270 on the same day, which is the real play.",
    origin: "CDG",
    destination: "JFK",
    carrier: "AF",
    cabin: "business",
    programId: "flying-blue",
    miles: 55000,
    taxesUsd: 270,
    travelDate: "2026-11-05",
    tags: ["air-france", "flying-blue", "psa"],
    likes: 64,
    daysAgo: 18,
  },
  {
    handle: "mileage_maven",
    title: "Etihad A350 J IAD→AUH on Aeroplan: 85k + $70 — EY is an Aeroplan partner now",
    body: "People keep missing this: Etihad awards on Aeroplan without Etihad's surcharges. Business Studio on the A350-1000. Onward AUH→MLE in Y for 10k more.",
    origin: "IAD",
    destination: "AUH",
    carrier: "EY",
    cabin: "business",
    programId: "aeroplan",
    miles: 85000,
    taxesUsd: 70,
    travelDate: "2027-02-01",
    tags: ["etihad", "aeroplan", "middle-east"],
    likes: 119,
    daysAgo: 19,
  },
  {
    handle: "avgeek_anna",
    title: "Qantas A380 F LAX→SYD: 144.6k Qantas points + $360 — found with the Kestrel calendar",
    body: "Qantas releases F space to its own members earlier than partners. The calendar view showed 3 dates in Feb. Citi → Qantas 1:1 took 2 days. Pajamas and the fine dining still beat most airlines.",
    origin: "LAX",
    destination: "SYD",
    carrier: "QF",
    cabin: "first",
    programId: "qantas-frequent-flyer",
    miles: 144600,
    taxesUsd: 360,
    travelDate: "2027-02-20",
    tags: ["qantas", "a380", "australia", "first-class"],
    likes: 156,
    daysAgo: 20,
  },
  {
    handle: "pointsdad",
    title: "Iberia Avios: BOS→MAD business 34k off-peak + $90 — no surcharges, A350",
    body: "Iberia Plus off-peak for the transatlantic at 34k one-way. Taxes under $100 because Iberia doesn't pile on YQ like BA. Transferred Chase UR → Iberia 1:1 (took ~24h). Kids in economy for 17k each.",
    origin: "BOS",
    destination: "MAD",
    carrier: "IB",
    cabin: "business",
    programId: "iberia-plus",
    miles: 34000,
    taxesUsd: 90,
    travelDate: "2027-04-12",
    tags: ["iberia", "avios", "off-peak", "spain"],
    likes: 108,
    daysAgo: 21,
  },
  {
    handle: "theredeye",
    title: "Aer Lingus JFK→DUB business for 50k Avios + $60 — easiest Europe award there is",
    body: "Aer Lingus via Avios (BA or Aer Club) in business is 50k off-peak from the East Coast with tiny taxes. Pre-clear US immigration in Dublin on the way back. A330 seat is older but lie-flat.",
    origin: "JFK",
    destination: "DUB",
    carrier: "EI",
    cabin: "business",
    programId: "aer-lingus-aerclub",
    miles: 50000,
    taxesUsd: 60,
    travelDate: "2026-11-30",
    tags: ["aer-lingus", "avios", "ireland"],
    likes: 92,
    daysAgo: 22,
  },
  {
    handle: "suitelife",
    title: "Korean Air Prestige Suites LAX→ICN for 62.5k Skypass + $50 — A380 upper deck",
    body: "Skypass is transferable from Marriott (3:1) and now from Bilt/Citi. The Prestige Suites are a 1-2-1 lie-flat; LAX–ICN daytime flight with the 'Seoul time' bibimbap. One-way awards allowed since 2023.",
    origin: "LAX",
    destination: "ICN",
    carrier: "KE",
    cabin: "business",
    programId: "korean-air-skypass",
    miles: 62500,
    taxesUsd: 50,
    travelDate: "2027-05-09",
    tags: ["korean-air", "skypass", "a380"],
    likes: 88,
    daysAgo: 24,
  },
  {
    handle: "jetsetjules",
    title: "Alila Ventana Big Sur: 45k/night Hyatt, all-inclusive, cash $1,900+",
    body: "Cat 8 peak. All meals and drinks included on points, which makes the math absurd: ~4.2¢/point. Glass house with the Pacific fog rolling in. Two nights was plenty, it's remote.",
    destination: "SFO",
    programId: "world-of-hyatt",
    miles: 90000,
    taxesUsd: 0,
    travelDate: "2027-06-14",
    tags: ["hyatt", "big-sur", "all-inclusive", "hotels"],
    likes: 174,
    daysAgo: 26,
  },
  {
    handle: "mileage_maven",
    title: "Air Canada Signature Class YVR→NRT, 55k Aeroplan + $45 — Pacific zone under 5,000 miles",
    body: "YVR→NRT is 4,680 miles so Aeroplan prices it in the lower Pacific band. 787-9 Signature pods. Chase UR → Aeroplan. Good Pacific starter award for people new to this.",
    origin: "YVR",
    destination: "NRT",
    carrier: "AC",
    cabin: "business",
    programId: "aeroplan",
    miles: 55000,
    taxesUsd: 45,
    travelDate: "2027-04-22",
    tags: ["air-canada", "aeroplan", "japan"],
    likes: 131,
    daysAgo: 28,
  },
];

export const SEED_TRANSFER_BONUSES = [
  { from: "amex-mr", to: "virgin-atlantic-flying-club", percent: 30, startsAt: "2026-09-15", endsAt: "2026-11-15", note: "Amex Membership Rewards → Virgin Atlantic 30% bonus" },
  { from: "chase-ur", to: "aeroplan", percent: 25, startsAt: "2026-10-01", endsAt: "2026-10-31", note: "Chase Ultimate Rewards → Aeroplan 25% bonus" },
  { from: "citi-ty", to: "qatar-privilege-club", percent: 25, startsAt: "2026-09-20", endsAt: "2026-10-20", note: "Citi ThankYou → Qatar Privilege Club 25% bonus" },
  { from: "bilt", to: "flying-blue", percent: 50, startsAt: "2026-10-01", endsAt: "2026-10-01", note: "Bilt Rent Day → Flying Blue 50% (Rent Day only)" },
  { from: "capital-one", to: "avianca-lifemiles", percent: 20, startsAt: "2026-10-05", endsAt: "2026-11-05", note: "Capital One → LifeMiles 20% bonus" },
];

export const SEED_BALANCES: Record<string, { programId: string; amount: number; status?: string; expiresAt?: string }[]> = {
  explorer: [
    { programId: "amex-mr", amount: 185400 },
    { programId: "chase-ur", amount: 92150 },
    { programId: "capital-one", amount: 61000 },
    { programId: "bilt", amount: 24300 },
    { programId: "aeroplan", amount: 45200, status: "25K" },
    { programId: "alaska-mileage-plan", amount: 71000, status: "MVP Gold" },
    { programId: "world-of-hyatt", amount: 38000, status: "Explorist" },
    { programId: "united-mileageplus", amount: 12400, expiresAt: "2027-03-01" },
  ],
};

export const SEED_ALERTS: Record<string, { name: string; origins: string[]; destinations: string[]; dateFrom: string; dateTo: string; cabin: "economy" | "premium" | "business" | "first"; passengers: number; maxMiles?: number; programs?: string[] }[]> = {
  explorer: [
    { name: "Tokyo in sakura season, lie-flat", origins: ["JFK", "EWR"], destinations: ["HND", "NRT"], dateFrom: "2027-03-20", dateTo: "2027-04-10", cabin: "business", passengers: 2, maxMiles: 90000 },
    { name: "Lisbon long weekend", origins: ["BOS", "JFK"], destinations: ["LIS"], dateFrom: "2027-05-01", dateTo: "2027-06-15", cabin: "business", passengers: 1, maxMiles: 60000 },
    { name: "Any first class to Europe", origins: ["NYC"], destinations: ["FRA", "LHR", "CDG", "MXP"], dateFrom: "2026-11-01", dateTo: "2027-02-28", cabin: "first", passengers: 1 },
  ],
};
